hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "config/crash_assistant/config.toml"

[[files]]
file = "config/modpack_defaults/config/bcc.json"

[[files]]
file = "config/modpack_defaults/config/dynamic_fps.json"

[[files]]
file = "config/modpack_defaults/config/ferritecore.mixin.properties"

[[files]]
file = "config/modpack_defaults/config/kerria.json"

[[files]]
file = "config/modpack_defaults/config/modernfix-mixins.properties"

[[files]]
file = "config/modpack_defaults/config/modmenu.json"

[[files]]
file = "config/modpack_defaults/config/moreculling.toml"

[[files]]
file = "config/modpack_defaults/config/quick-pack.json"

[[files]]
file = "config/modpack_defaults/options.txt"

[[files]]
file = "mods/anti-smooth.pw.toml"
metafile = true

[[files]]
file = "mods/async-pack-scan.pw.toml"
metafile = true

[[files]]
file = "mods/asynclogger.pw.toml"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/configmanager.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/e4all.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fastserverpings.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/jasione.pw.toml"
metafile = true

[[files]]
file = "mods/kerria-opt.pw.toml"
metafile = true

[[files]]
file = "mods/kilt.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/nondirectionaldamagetiltfix.pw.toml"
metafile = true

[[files]]
file = "mods/obe.pw.toml"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/simply-no-shading.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
metafile = true

[[files]]
file = "mods/vertical-bobbing.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/wonderland-jar.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
metafile = true
