name = "Wonderfabrica"
author = "Ratchet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8705a1884da79ee75b5201444ac21147cab4819846d52d4c8c242cb17a83d0c9"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
