name = "Wonderfabrica"
author = "Ratchet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1960952e5874d9b6fbfa887080a0f3453d3f76829fcc3a9e98d676227ef8d09d"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
